### PR TITLE
create Agent Activity API docs

### PR DESCRIPTION
**Pull request by nirlelp**

### CODE REVIEW

**Comment by jasmith-lp** [comment]
@nirlelp there are some errors in the files, please correct before and confirm if this work is then ready to be merged.

**Comment by mashkenazy** [comment]
@jasmith-lp where can we see the source of the errors?

**Comment by jasmith-lp** [comment]
> @jasmith-lp where can we see the source of the errors?

https://github.com/LivePersonInc/developers-community/pull/1365/checks?check_run_id=3170227776

**Comment by mashkenazy** [comment]
@nirlelp seems like the erros are with links:

> The permalink is invalid found: agent-activity-api-methods-get-status-changes.html
Expected permalink: agent-activity-api-get-status-changes.html 

> The permalink is invalid found: agent-activity-api-error-codes.html
Expected permalink: agent-activity-api-errorcodes.html 

> Page name: ErrorCodes in pages/Documents/Reporting/AgentActivityAPI/error-codes.md des not match the layout spec: Error Codes

**Comment by nirlelp** [comment]
Thanks,

I see that I'm missing subfoldername: Methods in Get Status Changes.
and I see the other page name should be Error Codes with a space, that's a
typo.

I will commit the changes to the PR, but it's not ready for publication yet.



On Wed, Jul 28, 2021 at 2:09 PM mashkenazy ***@***.***> wrote:

> @nirlelp
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nirlelp&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=IVkCNqE2y3Qnj4jZ95-RBe8cz6OmMal1MNzJnVBiXE0&m=NNhqmPceKwqLZcKeA907Rf7io0MZYntEm7m_IbXu9pg&s=CnwcZD3a33z7kbFR9eo0wEJItNkX4YIPaiT-cvhMm4k&e=>
> seems like the erros are with links:
>
> The permalink is invalid found:
> agent-activity-api-methods-get-status-changes.html
> Expected permalink: agent-activity-api-get-status-changes.html
>
> The permalink is invalid found: agent-activity-api-error-codes.html
> Expected permalink: agent-activity-api-errorcodes.html
>
> Page name: ErrorCodes in
> pages/Documents/Reporting/AgentActivityAPI/error-codes.md des not match the
> layout spec: Error Codes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_LivePersonInc_developers-2Dcommunity_pull_1365-23issuecomment-2D888223779&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=IVkCNqE2y3Qnj4jZ95-RBe8cz6OmMal1MNzJnVBiXE0&m=NNhqmPceKwqLZcKeA907Rf7io0MZYntEm7m_IbXu9pg&s=OE2UwUc6tov5F0BCRQUtB73sQec-8JyJEVuTEyT3Jds&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU5SXUFRP3EPZTLUC4IWASLTZ7QP7ANCNFSM5AX5QSIA&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=IVkCNqE2y3Qnj4jZ95-RBe8cz6OmMal1MNzJnVBiXE0&m=NNhqmPceKwqLZcKeA907Rf7io0MZYntEm7m_IbXu9pg&s=pLvndeiZ9kTj46eErwyNG5XFZ6XCLrlGRSyty-5BDhY&e=>
> .
>


-- 

Nir Leibovitch
SDE III
T: +972-74-700-4768
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Making life easier for people and brands everywhere through trusted
conversational AI
<https://www.liveperson.com/resources/news/liveperson-named-one-of-fast-companys-most-innovative-companies/?utm_medium=email&utm_source=gmail&utm_campaign=signature&utm_content=fastco>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Pull request merged**
