### PR TITLE
:memo: Added sso support

### PR DESCRIPTION
**Pull request by jplieninger**

### CODE REVIEW

**Comment by EdenKupe** [comment]
Hey,

What are you trying to do on line 16? Is that supposed to be a note?

**Comment by jplieninger** [comment]
Hi Eden,
it's supposed to be a blockquote. I tried it locally, it worked there.

**Comment by EdenKupe** [comment]
Got it, it won't work on the site itself. I'll put it inside a note box, blue with an eye icon :)

**Comment by EdenKupe** [comment]
Or actually, maybe it will work on the site itself but we don't really use them so I'll go with the note box anyway :)

**Comment by jplieninger** [comment]
Perfect. Thanks.

**Pull request merged**
