### PR TITLE
Javascript and java client documentation + error codes ( Please do not merge yet)

### PR DESCRIPTION
**Pull request by sschwarz96**
Could you please just deploy it to staging or whatever branch is internally available. There is still some links to the internal github but I would like the testing team to be able to access the documentation as they have to do QA before open sourcing. Once theyre done we can open source the two projects and replace the internal links so it can be merged to master.
Thank you :)

### CODE REVIEW

**Comment by EdenKupe** [comment]
Hey,

can you please re-open this PR to Staging? And if it's not ready to go to Staging, please open it as a draft, I'm a bit confused right now about when you'd like this merged to Staging.

**Comment by sschwarz96** [comment]
Hey Eden,

I am sorry for the confusion. Just to clear things up:
My intention is to make this documentation available internally so that our QA Team can access it but I do not want it to be accessible outside from the LivePerson network.
If this is what the staging branch offers, then please merge it, otherwise let me know which branch is the right one for that purpose.

**Comment by EdenKupe** [comment]
You're in the right place, merged :)

**Comment by sschwarz96** [comment]
Thank you :)

**Pull request merged**
