### PR TITLE
Update bestpractices.md

### PR DESCRIPTION
**Pull request by pmolensky**
The `Service Activity` (service) is replacing the previous content and not adding a new entry.

### CODE REVIEW

**Comment by EdenKupe** [comment]
Hey,

We tested this on our end and found that the EA is indeed acting as "Append" rather than "Replace". Have you implemented this and found a "Replace" behavior?

**Comment by pmolensky** [comment]
Yes, I have. See animated screengrabs:


The commands I used:
```
lpTag.sdes.push(
   {
        "type": "service",
        "service": {
           "topic": "order checkbook",
           "status": 0,
           "category": "finance",
           "serviceId": "service12"
        }
   }
);

lpTag.sdes.push(
   {
        "type": "service",
        "service": {
           "status": 1,
           "serviceId": "service12"
        }
   }
);

lpTag.sdes.push(
   {
        "type": "service",
        "service": {
           "topic": "next topic",
           "status": 3,
           "category": "test",
           "serviceId": "test987"
        }
   }
);
```
Ideally, I would like to see the same `serviceId` to act as **replace** and a new `serviceId` as an **append** 😉

**Comment by EdenKupe** [comment]
Got it! In that case, looks like you've stumbled upon a bug. Can you either open a case for Support or contact Sivan Dagan, the PM in charge of Engagement Attributes? They can feed it into the bug process and handle it.

Thanks!

**Comment by pmolensky** [comment]
I've created a case with support, closing this PR.

**Pull request closed without merging**
