### PR TITLE
Losslessly compressed images (115.5 MB saved)

### PR DESCRIPTION
**Pull request by j9t**
Compressed all images through ImageOptim. Result as per ImageOptim: Saved 115.5 MB out of 373.2 MB. 30.9% overall (up to 89.4% per file).

Signed-off-by: Jens Oliver Meiert <jens@meiert.com>

### CODE REVIEW

**Comment by j9t** [comment]
@XueliYue, @lp-gdoshi, do you know who can help get this PR reviewed? I believe it means some real gains, and as it’s been work to process I’d like to avoid it getting stale. (Happy to respond to any questions about this internally—prepared this on personal capacity.)

**Comment by XueliYue** [comment]
> @XueliYue, @lp-gdoshi, do you know who can help get this PR reviewed? I believe it means some real gains, and as it’s been work to process I’d like to avoid it getting stale. (Happy to respond to any questions about this internally—prepared this on personal capacity.)
@jasmith-lp may be right person.

**Comment by jasmith-lp** [comment]
Hey @XueliYue @j9t this seems like a good idea. Will we need to rebase afterwards to take advantage of the savings?

@lpbarber if we do this, we would need to abandon the current "staging" branch. Since it's very out of date is this ok to proceed?

**Comment by lpbarber** [comment]
@jasmith-lp - I think the right person to consult this with is @itay1313

**Comment by jasmith-lp** [comment]
@itay1313 can we delete the staging branch and start again there?
@lpbarber I ask about the staging branch because you previously put a lot of effort into it

**Review by itay1313 — APPROVED** [review]
let me know if u need help with merging this, strange conflict with the images

**Comment by j9t** [comment]
@itay1313, thought I had resolved the conflicts, but noticed that the PR added images back. Hadn’t squashed commits, either, therefore redoing the whole thing in a new PR. Will file when optimization is completed.

**Comment by itay1313** [comment]
sounds like a better solution thanks

**Pull request closed without merging**
