### PR TITLE
Simplify Clickable Mobile Content to SMS

### PR DESCRIPTION
**Pull request by pmolensky**
On Stackoverflow I found a comment to combine the number/message separator, without the need to distinguish between iOS or Android:
https://stackoverflow.com/a/38708066

I've tested the proposed solution to combine the separator. While the order of the characters is important, I found it working on both iOS and Android.
* Tested on Samsung S7 Edge / Android 8.0.0 / Chrome 67.0.3396.87
* Tested on iPhone 6s / iOS 11.4 / Safari

When you're able to confirm this solution, I think we can greatly simplify the mobile content configuration, especially without the need to add additional code to the brand's website.

### CODE REVIEW

**Comment by EdenKupe** [comment]
@orenkatz can you please review this?

**Comment by WildYorkies** [comment]
@pmolensky This is a great find! I would just like to add though, that many users would prefer to distinguish the two buttons for reporting purposes. So, perhaps your solution here can be included with the original docs somehow, not totally replacing the old one?

**Comment by pmolensky** [comment]
@WildYorkies agreed, there is indeed a benefit in keeping the device info for reporting, not only limited to clickable content :-)
_I have a personal preference to document a working setup and use, in this example, the device info as an extension on the codepackage, not only for content2SMS._

**Comment by EdenKupe** [comment]
Hey @pmolensky just circling back to this; master has undergone some changes since you opened this. Can I get you to close it and recommit your changes to the new documents? I'll then bug DevSupport again about reviewing this.

Thanks!

**Comment by pmolensky** [comment]
Sure @EdenKupe, see PR #243

**Pull request closed without merging**
