### PR TITLE
Added API/SDK overview page

### PR DESCRIPTION
**Pull request by j9t**

### CODE REVIEW

**Comment by j9t** [comment]
@itay1313, @mferreira-lp, would you both mind reviewing? (The important file is [the overview page itself](https://github.com/LivePersonInc/developers-community/pull/1783/files#diff-e0c85213fa6d111c4b111a2a2ad727e207b0dcb2fa06e3c4210ee6361e5abae9).)

The whole idea is based on there not being such an overview yet, but that this can make getting started a lot easier. Going forward, we (DX) will need to maintain this.

FYI @lkisoslive

**Review by lkisoslive — COMMENTED** [review]
I would change synch to sync if possible.

**Comment by j9t** [comment]
> I would change synch to sync if possible.

Yes—there weren’t many cases of this, so I changed it everywhere.

**Review by mferreira-lp — COMMENTED** [review]
Hi, a few comments:

- Line 34 in liveperson-apis-and-sdks.md has a different syntax from the others. Is it okay? 
- I realize this might not be easily done, but it might be good to logically group them in some way (use case, problem solved, etc.) to make the list easier to consume. Alphabetizing is one approach, but that seems only useful when you know the name of the API you want to use. Something to consider for a future iteration?
- Conversational AI exposes a single public API that I'm aware of for Intent Manager. It is documented here: https://developers.liveperson.com/intent-manager-external-apis-model-tester-external-apis.html ...Could this be added?

**Comment by j9t** [comment]
> * Conversational AI exposes a single public API that I'm aware of for Intent Manager. It is documented here: https://developers.liveperson.com/intent-manager-external-apis-model-tester-external-apis.html ...Could this be added?

@mferreira-lp—great catch; added! Thanks!

**Review by mferreira-lp — APPROVED** [review]
@j9t So sorry to nit pick on this, but could we perhaps pre-pend the API names for those 2 APIs with "Intent Manager"...? Or perhaps, "Conversational AI's Intent Manager XYZ API," where XYZ API is the link?

**Comment by j9t** [comment]
> @j9t So sorry to nit pick on this, but could we perhaps pre-pend the API names for those 2 APIs with "Intent Manager"...? Or perhaps, "Conversational AI's Intent Manager XYZ API," where XYZ API is the link?

@mferreira-lp, let’s consider moving this off-thread and to Slack; we’d need to define a line when we qualify an API name, and when not. (Do you have a suggestion?) The current system follows one model, using the name of the API as it’s used in our docs.

(I wonder, too, whether not adding something to the name would even be a big problem—the API page should make clear what it belongs to.)

**Pull request merged**
