### PR TITLE
docs: refer to LivePerson’s developer center and community

### PR DESCRIPTION
**Pull request by j9t**
(and make links relative to the repository URL)

### CODE REVIEW

**Review by lkisoslive — COMMENTED** [review]
Should we have it "Developer Center" everywhere like in the last doc? Here it is lower case entirely.

**Comment by j9t** [comment]
> Should we have it "Developer Center" everywhere like in the last doc? Here it is lower case entirely.

@lkisoslive, you mean, treat this like a name? How does “community” fit in—also with a capital “C”?

**Comment by lkisoslive** [comment]
I think these are names and should be capitalized. Let me know what you think.

**Review by lkisoslive — APPROVED** [review]

**Comment by j9t** [comment]
Let’s work with that. Pushed an update—please confirm if good to go. (Thanks!)

**Review by lkisoslive — APPROVED** [review]

**Comment by lkisoslive** [comment]
Approved! Thanks.

Liat

On 8 Aug 2022, at 13:15, Jens Oliver Meiert ***@***.***> wrote:

﻿
Let’s work with that. Pushed an update—please confirm if good to go. (Thanks!)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.
-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Pull request merged**
