### PR TITLE
Dx 20 images img

### PR DESCRIPTION
**Pull request by itay1313**
[DX-20](https://jira.liveperson.com/browse/DX-20)

### CODE REVIEW

**Review by itay1313 — COMMENTED** [review]
@j9t

**Review by j9t — COMMENTED** [review]
There are a lot of changes from "images/…" to "img/archive/…" (not the missing of a leading slash). Just to double-check, are these confirmed to fall back to the root?

**Comment by itay1313** [comment]
> 

yes I did it manually and check on local for each change

**Comment by j9t** [comment]
Thanks for confirming; let’s take some samples later to make sure everything is working.

**Review by j9t — APPROVED** [review]

**Pull request merged**
