### PR TITLE
Adds documentation for Faas java and js client including respective error codes

### PR DESCRIPTION
**Pull request by sschwarz96**
I kept the changes in yaml file as it worked fine on staging

### CODE REVIEW

**Comment by EdenKupe** [comment]
Hey @sschwarz96 ! Not clear on this line: 

"This is needed if you want to use the client to get all lambdas as it still relies on OAuth 1.0." What relies on OAuth 1.0? The client? Didn't you say above that you're using 2.0?

**Comment by EdenKupe** [comment]
Ready to go except for my one comment above :)

**Comment by LivePersonFaas** [comment]
I have changed the according paragraph. Let me know if it sounds more understandable now. 
Thank you :)

**Comment by sschwarz96** [comment]
I have changed the according paragraph. Hope it sounds more clear now. 
Let me know if it sounds better now :)

**Comment by EdenKupe** [comment]
Perfect, thanks!

**Pull request merged**
