### PR TITLE
fix: correct Node.js spelling (as per nodejs.org)

### PR DESCRIPTION
**Pull request by j9t**
Signed-off-by: Jens Oliver Meiert <jens@meiert.com>

### CODE REVIEW

**Comment by j9t** [comment]
@itay1313, would you mind? (Big fan of following protocol, so wouldn’t just want to skip reviews.)

**Comment by itay1313** [comment]
@j9t  Hey there is a conflict in this PR

**Review by itay1313 — CHANGES_REQUESTED** [review]
There is a conflict, please resolve

**Comment by j9t** [comment]
Resolved, @itay1313—please check again. (Thanks!)

**Pull request merged**
